version: '3'
services:
  #Postgres Service
  ts-db:
    image: timescale/timescaledb:2.0.0-pg12
    container_name: acs-ts-db
    restart: unless-stopped
    tty: true
    volumes:
      - "tspgdata:/var/lib/postgresql/data"
      - "./sourcefiles/postgresql/postgresql-ts.conf:/var/lib/postgresql/data/postgresql-ts.conf"
      - ../server.crt:/var/lib/postgresql/data/server.crt
      - ../server.key:/var/lib/postgresql/data/server.key
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=postgresql
    ports:
      - "5432:5432"
    networks:
      - acs-api_app-network

#Volumes
volumes:
  tspgdata:
    driver: local

networks:
  acs-api_app-network:
    external: true
