version: '3'
services:

  #PHP Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: acs-api
    container_name: acs-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/acs-api/
    volumes:
      - ./:/var/www/html/acs-api/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.16-alpine
    container_name: acs-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/acs-api
      - ./sourcefiles/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - backend
      - db

  #Postgres Service
  db:
    image: postgres:12-alpine
    container_name: acs-db
    restart: unless-stopped
    tty: true
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=postgresql
    ports:
      - "5432:5432"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

#Volumes
volumes:
  pgdata:
    driver: local
