version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: acs-api
    container_name: acs-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/acs-api/
    volumes:
      - ./:/var/www/html/acs-api/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.16-alpine
    container_name: acs-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      # - "8001:443"
    volumes:
      - ./src/acs-api:/var/www/html/acs-api
      - ./nginx/:/etc/nginx/sites-available
    networks:
      - app-network

  #Postgres Service
  db:
    image: postgres:12-alpine
    container_name: db
    restart: unless-stopped
    tty: true
    volumes:
         - "./sourcefiles/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=postgresql
    ports:
      - "5432:5432"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
