# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: calling azure pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
    # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
         azure-devops-project-url: ${{DEVOPS_PROJECT_URL}}
    # Name of the Azure Pipline to be triggered
         azure-pipeline-name: ${{DEVOPS_PIPELINE_NAME}}
    # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
         azure-devops-token: ${{DEVOPS_TOKEN}}
